# Generated by Django 2.2.4 on 2020-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20200819_0851'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='favorites',
            field=models.ManyToManyField(related_name='faved_by', to='login_app.User'),
        ),
    ]
