# Generated by Django 2.2.4 on 2020-08-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_sound_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='favorites',
            new_name='fav',
        ),
    ]
