# Generated by Django 2.2.4 on 2020-08-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20200819_0851'),
        ('upload', '0003_auto_20200827_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='fav',
        ),
        migrations.AddField(
            model_name='sound',
            name='fans',
            field=models.ManyToManyField(related_name='faves', to='login_app.User'),
        ),
    ]
